export const iconOptions = [
  { label: 'Wi-Fi', value: 'fa-wifi' },
  { label: 'TV', value: 'fa-tv' },
  { label: 'Ar-condicionado', value: 'fa-snowflake' },
  { label: 'Toalhas', value: 'fa-bath' },
  { label: 'Cozinha', value: 'fa-utensils' },
  { label: 'Piscina', value: 'fa-swimmer' },
  { label: 'Pet Friendly', value: 'fa-dog' },
  { label: 'Café da manhã', value: 'fa-mug-hot' },
  { label: 'Banheira', value: 'fa-hot-tub' },              
  { label: 'Hidromassagem', value: 'fa-spa' },
  { label: 'Lareira', value: 'fa-fire' },
  { label: 'Netflix', value: 'fa-film' },                 
  { label: 'Micro-ondas', value: 'fa-microwave' },         
  { label: 'Frigobar', value: 'fa-wine-bottle' },
  { label: 'Secador de cabelo', value: 'fa-wind' },
  { label: 'Mesa para trabalho', value: 'fa-chair' },
  { label: 'Vista para o mar', value: 'fa-water' },
  { label: 'Serviço de quarto', value: 'fa-concierge-bell' },
  { label: 'Acessível para cadeirantes', value: 'fa-wheelchair' },
  { label: 'Churrasqueira', value: 'fa-fire-burner' },
  { label: 'Varanda', value: 'fa-building' },
];
